### ISSUE TITLE
number of bytes to skip in streamout

### ISSUE THREAD

**Issue by ggrenier** [SDHCAL/EventBuilder#1]
A parametrisation of the number of bytes to skip at the start of the raw data buffer should be added instead of the currently hardcoded number in SDHCAL_RawBuffer_Navigator constructor : 
 _DIFstartIndex=DIFUnpacker::getStartOfDIF(_buffer.buffer(),_buffer.getsize(),24); //92 was here

**Comment by flagarde** [comment]
done

**Comment by ggrenier** [comment]
But the line _DIFstartIndex=DIFUnpacker::getStartOfDIF(_buffer.buffer(),_buffer.getsize(),24); //92 was here still have still seems to have the 24 hardcoded in the code. What was changed ?

**Comment by flagarde** [comment]
This time I think is done
